stages:
  - lint
  - build

yaml:
  image: python:alpine
  stage: lint
  before_script:
    - pip install yamllint
  script:
    - yamllint meta/*.yml

debian:
  image: ligo/base:stretch
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes install equivs ruby
  script:
    - ruby generate.rb
    - for i in stage/*/deb/; do ( cd $i; equivs-build control ); done
    - mkdir debs
    - for i in stage/*/deb/*.deb; do cp $i debs; done
  artifacts:
    expire_in: 3h
    paths:
      - debs

rhel:
  image: ligo/base:el7
  stage: build
  before_script:
    - yum --assumeyes install rpm-build rpmlint ruby
  script:
    - ruby generate.rb
    - for i in stage/*/rpm/*.spec; do rpmlint $i; rpmbuild -ba $i; done
    - mkdir rpms srpms
    - mv rpmbuild/RPMS/noarch/*.rpm rpms
    - mv rpmbuild/SRPMS/*.rpm srpms
  artifacts:
    expire_in: 3h
    paths:
      - rpms
      - srpms
