stages:
  - lint
  - build

yaml:
  image: python:alpine
  stage: lint
  before_script:
    - pip install yamllint
  script:
    - yamllint meta/*.yml

rpmlint:
  image: ligo/base:el7
  stage: lint
  before_script:
    - yum --assumeyes install ruby rpmlint
  script:
    - ruby generate.rb
    - for i in stage/*/rpm/*.spec; do echo $i; rpmlint $i; done

debian:
  image: ligo/base:stretch
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes install equivs ruby
  script:
    - ruby generate.rb
    - for i in stage/*/deb/; do ( cd $i; equivs-build control ); done

rhel:
  image: ligo/base:el7
  stage: build
  before_script:
    - yum --assumeyes install rpm-build ruby
  script:
    - ruby generate.rb
    - for i in stage/*/rpm/*.spec; do rpmbuild -ba $i; done
