stages:
  - lint
  - build

check:
  image: python:alpine
  stage: lint
  before_script:
    - pip install yamllint
  script:
    - yamllint meta/*.yml

debian:
  image: ligo/base:stretch
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes install equivs ruby
  script:
    - ruby generate.rb
    - for i in stage/*/deb/; do ( cd $i; equivs-build control ); done
